server:
  port: 8085

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sisp.dao.entity
  configuration:
    cache-enabled: true

spring:
  datasource:
    url: jdbc:mysql://8.130.118.152:3306/questionnaire?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: wyx
    password: '123456'
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    banner-mode: off